#!/bin/sh
RCROOT=$(cd $(dirname $0)/.. && pwd)
KERNEL=$(uname -s)

if [ $KERNEL = Darwin ]; then
  if type brew; then
    echo 'homebrew is already installed'
  else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi
fi

if [ ! -e $HOME/.zsh/colors/dircolors-solarized ]; then
  git clone https://github.com/seebi/dircolors-solarized $HOME/.zsh/colors/dircolors-solarized
fi

cp -n $RCROOT/secrets $HOME/.secrets
