require './utils.rb'

cask_args appdir: "/Applications"
tap "mongodb/brew"

brew "asdf"
brew "cocoapods"
brew "coreutils"
brew "ctags"
brew "curl"
brew "direnv"
brew "ffmpeg"
brew "gawk"
brew "ghq"
brew "gibo"
brew "git"
brew "gpg"
brew "go"
brew "highlight"
brew "jq"
brew_skip_m1 "mas"
brew "mongodb-community"
brew "neovim"
brew "pcre"
brew "peco"
brew "rcm"
brew "reattach-to-user-namespace"
brew "ssh-copy-id"
brew "terminal-notifier"
brew "tig"
brew "tldr"
brew "tmux"
brew "zsh"
brew "zsh-syntax-highlighting"

cask "alfred"
cask "coteditor"
cask "dash"
cask "discord"
cask "docker"
cask "google-chrome"
cask_skip_m1 "google-cloud-sdk"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "kindle"
cask "sequel-pro"
cask "slack"
cask "sonic-pi"
cask "spotify"
cask "visual-studio-code"

if is_m1?
    puts "Skip installing MAS applications because mas command not supported m1 processor"
    return
end

# App Store applications
mas "LastPass", id: 926036361
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
